---
title: "Prep Worksheet - Project 1"
author: "William Fowle"
---

**Overview:** Because there’s some variation in how students approach this assignment, this worksheet serves two purposes. First, it helps you plan out your resume based on your analysis of the position you chose. Second, it helps me understand how you’re approaching this assignment. For example, I want to know if you’re actually applying to a position or if this is your first time creating a resume.

**Instructions:** Please answer each of the questions below in complete sentences.

1.  **If you’re not using the 2311 internship job ad, tell me about the job ad you chose and explain why you chose it.** Remember, you can choose (1) an entry-level position or internship in your field OR (2) the 2311 internship. If you choose option one, please include the job ad with your submission for this assignment. You can upload it as a PDF or an image file (last I checked, .PNG, .JPG, and .JPEG all rendered on Blackboard).

I'm using the Business Development Intern at 2311 Climate Solutions job ad.

2.  **Describe your target organization as a primary audience.** What are they looking for in a candidate? What’s important to them? What beliefs and values are important to the organization? Can you summarize its mission statement?

2311 Climate Tech solutions works with industrial partners to help take industrial waste product and convert it into economically valuable byproducts. They are a team that has partnerships across academia, industry, and other climate technology stakeholders according to their job ad. The job summary they offer states that the role would be responsible for establishing growth and commercialization strategy. All morals aside, as a company their primary revenue source is their ability to partner with companies that have excess industrial waste, such companies typically spend a lot of their fixed costs on disposing of that waste, ergo strong partnerships with industrial companies whose waste we can turn into economically viable byproducts are going to likely be 2311 Climate Solutions' primary customer. To 2311 Climate Solutions the main mission statement is to, "Close the carbon and materials loop". More simply stated they want to help create a cleaner and more efficient industrial process by innovating in the waste product field.

3.  **Think back to the “Job Ads & Resumes in Your Field” discussion assignment.** What were the patterns and trends you noticed in how professionals in your intended field organize their resumes? What were the best practices you described?

The biggest thing that I saw was that they focused on what they delivered in their previous experience. They would state their achievements in pattern similar to the STAR pattern described in Chapter 11. This is an important step to take in organizing any resume because any potential employer is not going just want to know what your last job was, but also, what did you do there? How does that experience relate to what I'm potentially going to have them doing here? While there are other things you can do to get noticed, I think the most impactful thing you can do is to be able to speak to your past experience with very explainable outcomes.

4.  **Based on your responses to questions 3 and 4 (and the recommendations in chapter 11), what sections will you include in your resume other than education and experience?** While we don't want any blank sections (and you definitely shouldn't lie), it's fine to include a section that you'll continue to update over the course of your academic and professional career. For example, your only certification might be CPR or your only programming language might be Python (beginner). It's fine if some sections seem a little sparse for the time being.

A big one in the engineering field is the contact portion. Not just listing your email and LinkedIn but also listing a personal website or a place recruiters/hiring managers can go to get a tangible look at your work product. This is especially relevant for software engineers but realistically any engineer should have a Github profile or a website where they've thoroughly listed out their experience and can show their understanding and skill. A good showcase is always going to stand out to potential employers and there's only so much you can do on a resume to stand out, therefore, having a clear way for someone to learn more about you and your skill set it a MUST nowadays.

5.  **Based on your analysis of the organization and position requirements, what reservations or objections could your audience have about hiring you for the position? How can you address or overcome those reservations or objections?** For example, is your exact major similar to those listed in the job ad but not an exact match? Do you have one year of experience instead of two?

If I were in their shoes I think the biggest thing I would be looking at is my experience with climate technology and industrial products. In the past I have relevant business development experience and I would be a good fit based on that. However, climate technologies is a very niche field and having a good understanding of that industry is going to play a key role in being a valid strategic thinker, which is what they're asking for. So, when you're trying to get your first job in an industry that you're not familiar with you always want to emphasize your ability to learn a lot and quickly. So I would point to my past experience in places where I took my understanding or skill-set from 0-100. I would also want to provide them a realistic timeline as to what I think I can do in terms of getting caught up. It also helps to show that you like to go above and beyond by doing thorough research on their product and industry before any potential interview to let them know how serious you are about understanding the field and being a strong contributor.